"""especializacao adicionado diretamente no medico

Revision ID: 31d4598abce2
Revises: ac5ddf5fa7f5
Create Date: 2026-09-08 08:26:53.831330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31d4598abce2'
down_revision: Union[str, Sequence[str], None] = 'ac5ddf5fa7f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('especializacao')
    op.drop_table('especializacao_medico')
    op.add_column('medico', sa.Column('especializacao', sa.String(length=70), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medico', 'especializacao')
    op.create_table('especializacao_medico',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('id_medico', sa.INTEGER(), nullable=False),
    sa.Column('id_especializacao', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['id_especializacao'], ['especializacao.id'], ),
    sa.ForeignKeyConstraint(['id_medico'], ['medico.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('especializacao',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=70), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    # ### end Alembic commands ###
