"""add default 0 na unidade de saude

Revision ID: 6209d894a600
Revises: 6a0c4b0468ce
Create Date: 2026-09-03 09:58:05.042251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6209d894a600'
down_revision: Union[str, Sequence[str], None] = '6a0c4b0468ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
