"""add csrf_token nas sessoes

Revision ID: 6648597111fb
Revises: af54fdc66715
Create Date: 2026-09-10 07:39:40.349944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6648597111fb'
down_revision: Union[str, Sequence[str], None] = 'af54fdc66715'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('csrf_token', sa.String(length=64), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'csrf_token')
    # ### end Alembic commands ###
