"""add localizacao com link no google maps

Revision ID: 6a0c4b0468ce
Revises: 40098b4b567b
Create Date: 2026-09-03 09:07:24.353683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a0c4b0468ce'
down_revision: Union[str, Sequence[str], None] = '40098b4b567b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unidade_saude', sa.Column('localizacao_exibicao', sa.String(length=255), nullable=False))
    op.add_column('unidade_saude', sa.Column('localizacao_link_mapa', sa.String(length=255), nullable=True))
    op.drop_column('unidade_saude', 'localizacao')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unidade_saude', sa.Column('localizacao', sa.VARCHAR(length=255), nullable=False))
    op.drop_column('unidade_saude', 'localizacao_link_mapa')
    op.drop_column('unidade_saude', 'localizacao_exibicao')
    # ### end Alembic commands ###
