"""add tabela de sessões

Revision ID: af54fdc66715
Revises: 1f0293be01ec
Create Date: 2026-09-09 07:50:41.284866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af54fdc66715'
down_revision: Union[str, Sequence[str], None] = '1f0293be01ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('unidade_saude_id', sa.Integer(), nullable=False),
    sa.Column('expira_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['unidade_saude_id'], ['unidade_saude.id'], ),
    sa.PrimaryKeyConstraint('token_hash')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session')
    # ### end Alembic commands ###
