"""correcao para unique na especializacao

Revision ID: d3a5474d89da
Revises: 107ad0df068e
Create Date: 2026-09-02 21:07:57.066858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3a5474d89da'
down_revision: Union[str, Sequence[str], None] = '107ad0df068e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('especializacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=70), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('medicamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('dosagem', sa.String(length=40), nullable=False),
    sa.Column('forma', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unidade_saude',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_login', sa.String(length=100), nullable=False),
    sa.Column('nome_exibicao', sa.String(length=100), nullable=False),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.Column('localizacao', sa.String(length=255), nullable=False),
    sa.Column('aberto', sa.Boolean(), nullable=False),
    sa.Column('horario_abertura', sa.String(length=20), nullable=False),
    sa.Column('horario_fechamento', sa.String(length=20), nullable=False),
    sa.Column('pessoas_fila_atendimento', sa.Integer(), nullable=False),
    sa.Column('pessoas_atendidas', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('especializacao_medico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_medico', sa.Integer(), nullable=False),
    sa.Column('id_especializacao', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_especializacao'], ['especializacao.id'], ),
    sa.ForeignKeyConstraint(['id_medico'], ['medico.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('falta_medicamento_unidade_saude',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_unidade_saude', sa.Integer(), nullable=False),
    sa.Column('id_medicamento', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_medicamento'], ['medicamento.id'], ),
    sa.ForeignKeyConstraint(['id_unidade_saude'], ['unidade_saude.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unidade_saude_medico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_medico', sa.Integer(), nullable=False),
    sa.Column('id_unidade_saude', sa.Integer(), nullable=False),
    sa.Column('status_medico_unidade_saude', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['id_medico'], ['medico.id'], ),
    sa.ForeignKeyConstraint(['id_unidade_saude'], ['unidade_saude.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unidade_saude_medico')
    op.drop_table('falta_medicamento_unidade_saude')
    op.drop_table('especializacao_medico')
    op.drop_table('unidade_saude')
    op.drop_table('medico')
    op.drop_table('medicamento')
    op.drop_table('especializacao')
    # ### end Alembic commands ###
